name: Deploy

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'  # Adjust the .NET version as needed

    - name: Publish .NET Core app
      run: dotnet publish BuildMpvUpscale2xAnimeJaNai/BuildMpvUpscale2xAnimeJaNai.csproj -c Release -o publish

    - name: Run the console app
      run: ./publish/BuildMpvUpscale2xAnimeJaNai.exe

    - name: Install 7zip
      run: choco install 7zip -y

    - name: Create 7zip archive of the artifact
      run: 7z a -t7z -mx=9 mpv-upscale-2x_animejanai-full-package-${{ github.event.inputs.release_version }}.7z ./publish/mpv-upscale-2x_animejanai-v${{ github.event.inputs.release_version }}

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.inputs.release_version }}
        release_name: ${{ github.event.inputs.release_version }}
        draft: true
        prerelease: false
        artifacts: mpv-upscale-2x_animejanai-full-package-${{ github.event.inputs.release_version }}.7z
        token: ${{ secrets.GITHUB_TOKEN }}